% ELEC404 Introduction to Robotics 
% Simulation Project
% By: Zeng Tao
% This file returns the outputs of InvJ block in simulink, RRA model
% Which are the first derivation of angle t2, t3 and t4

function ThetaDot=InvJ(x)
% the inputs should be theta2 theta3 and theta4, Vx, Vy, Vz
t2=x(1);
t3=x(2);
t4=x(3);
V=x(4:6);

% Results from "Jacobian_p.m"
InvJ = [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   200*sin(t2)/(-49*sin(t3)*cos(t4)-49*cos(t3)*sin(t4)-250*sin(t3)*sin(t4)+250*cos(t3)*cos(t4)+234*sin(t3)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  -200*cos(t2)/(-49*sin(t3)*cos(t4)-49*cos(t3)*sin(t4)-250*sin(t3)*sin(t4)+250*cos(t3)*cos(t4)+234*sin(t3)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0;
 100/117*(-15000*sin(t2)*sin(t3)*sin(t4)+60099*cos(t2)*cos(t4)^2-24500*cos(t2)*cos(t4)*sin(t4)-24500*cos(t2)*cos(t3)*sin(t3)+11466*cos(t2)*cos(t4)-11466*cos(t2)*cos(t3)^2*cos(t4)+58500*cos(t2)*sin(t4)-58500*cos(t2)*cos(t3)^2*sin(t4)+60099*cos(t2)*cos(t3)^2+15000*sin(t2)*cos(t3)*cos(t4)-2940*sin(t2)*cos(t3)*sin(t4)-2940*sin(t2)*sin(t3)*cos(t4)-62500*cos(t2)-120198*cos(t2)*cos(t3)^2*cos(t4)^2+49000*cos(t2)*sin(t3)*cos(t4)^2*cos(t3)+49000*cos(t2)*cos(t3)^2*sin(t4)*cos(t4)+11466*cos(t2)*sin(t3)*cos(t3)*sin(t4)-58500*cos(t2)*sin(t3)*cos(t3)*cos(t4)+120198*cos(t2)*sin(t3)*cos(t4)*cos(t3)*sin(t4))/(-60099*sin(t3)*cos(t4)*sin(t4)-24500*sin(t3)*cos(t4)^2+2401*cos(t3)-24500*cos(t3)*sin(t4)*cos(t4)+58500*sin(t3)*cos(t4)-11466*sin(t3)*sin(t4)+12250*sin(t3)+60099*cos(t3)*cos(t4)^2), -100/117*(62500*sin(t2)-11466*sin(t2)*sin(t3)*sin(t4)*cos(t3)+58500*sin(t2)*cos(t3)*cos(t4)*sin(t3)+15000*cos(t2)*cos(t3)*cos(t4)-15000*cos(t2)*sin(t3)*sin(t4)-2940*cos(t2)*cos(t3)*sin(t4)-2940*cos(t2)*sin(t3)*cos(t4)-49000*sin(t2)*cos(t3)*cos(t4)^2*sin(t3)-11466*sin(t2)*cos(t4)-60099*sin(t2)*cos(t4)^2-60099*sin(t2)*cos(t3)^2-120198*sin(t2)*cos(t3)*cos(t4)*sin(t3)*sin(t4)+120198*sin(t2)*cos(t3)^2*cos(t4)^2-58500*sin(t2)*sin(t4)+11466*sin(t2)*cos(t3)^2*cos(t4)+58500*sin(t2)*cos(t3)^2*sin(t4)+24500*sin(t2)*sin(t4)*cos(t4)-49000*sin(t2)*sin(t4)*cos(t4)*cos(t3)^2+24500*sin(t2)*cos(t3)*sin(t3))/(-60099*sin(t3)*cos(t4)*sin(t4)-24500*sin(t3)*cos(t4)^2+2401*cos(t3)-24500*cos(t3)*sin(t4)*cos(t4)+58500*sin(t3)*cos(t4)-11466*sin(t3)*sin(t4)+12250*sin(t3)+60099*cos(t3)*cos(t4)^2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -100/117*(64901*sin(t3)*cos(t4)^2+64901*cos(t3)*sin(t4)*cos(t4)-2401*sin(t3)+12250*cos(t3))/(-2401+64901*cos(t4)^2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -100/117*(49*cos(t2)*sin(t3)*cos(t4)+49*cos(t2)*cos(t3)*sin(t4)+250*cos(t2)*sin(t3)*sin(t4)-250*cos(t2)*cos(t3)*cos(t4)+60*sin(t2)-234*cos(t2)*sin(t3))/(-49*sin(t4)+250*cos(t4)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          100/117*(-49*sin(t2)*sin(t3)*cos(t4)-49*sin(t2)*cos(t3)*sin(t4)-250*sin(t2)*sin(t3)*sin(t4)+250*sin(t2)*cos(t3)*cos(t4)+60*cos(t2)+234*sin(t2)*sin(t3))/(-49*sin(t4)+250*cos(t4)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              100/117*(250*sin(t3)*cos(t4)+49*cos(t3)*cos(t4)-49*sin(t3)*sin(t4)-234*cos(t3)+250*cos(t3)*sin(t4))/(-49*sin(t4)+250*cos(t4))];
 
 

ThetaDot=InvJ*V;